MoneyManager/urls.py
from django.contrib import admin
from django.urls import path
from MoneyManagerApp import views
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns = [
    url('^$', views.DashboardView.as_view(), name='DashboardView'),
    url('^dashboard/$', views.DashboardView.as_view(), name='DashboardView'),
    url('^dashboard/(?P<account_id>[0-9]+)/$', views.DashboardView.as_view(), name='DashboardView'),
    url(r'^signup/$', views.SignUpView.as_view(), name='SignupView'),
    url(r'^login/$', auth_views.LoginView.as_view(), name='LoginView'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='LogoutView'),
    url(r'accountcreate/$', views.AccountCreateView.as_view(), name='AccountCreateView'),
    url(r'transactioncreate/(?P<type>.+)/$', views.TransactionCreateView.as_view(), name='TransactionCreateView'),
    url(r'^(?P<pk>[0-9]+)/accountdelete/$', views.AccountDeleteView.as_view(), name='AccountDeleteView'),
    url(r'^(?P<pk>[0-9]+)/transactiondelete/$', views.TransactionDeleteView.as_view(), name='TransactionDeleteView'),
    path('admin/', admin.site.urls),
]

MoneyManagerApp/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
from MoneyManager.settings import INCOME_CATEGORY_CHOICES, OUTCOME_CATEGORY_CHOICES

class Currency(models.Model):
    name = models.CharField(_('Currency name'), max_length=20)
    short_name = models.CharField(_('Currency short name'), max_length=3)
    symbol = models.CharField(_('Currency sign'), max_length=3)
    # if true then display symbol before number for ex. $4 otherwise display symbol after 4€
    prefix = models.BooleanField(_('Prefix'), default=False)

    def __str__(self):
        return '%s (%s)' % (self.name, self.symbol)

    def display(self, amount):
        return '%s%.2f' % (self.symbol, amount) if self.prefix else '%.2f%s' % (amount, self.symbol)

class User(AbstractUser):
    pass

    def __str__(self):
        return self.email

class Account(models.Model):
    name = models.CharField(_('Account name'), max_length=10)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='accounts')
    balance = models.DecimalField(_('Balance'), max_digits=8, decimal_places=2)
    currency = models.ForeignKey(Currency, on_delete=models.CASCADE, default='')
    BANKACCOUNT = 'BA'
    CASH = 'CH'
    CARD = 'CD'
    ACCOUNT_TYPE_CHOICES = (
        (BANKACCOUNT, _('Bank account')),
        (CASH, _('Cash')),
        (CARD, _('Card')),
    )
    type = models.CharField(_('Account type'), max_length=2, choices=ACCOUNT_TYPE_CHOICES, default=BANKACCOUNT)

    def print_balance(self):
        return self.currency.display(self.balance)

    def set_balance(self, transaction):
        if transaction.account.id == self.id:
            type = transaction.type
            if type == 'I':
                self.balance += transaction.amount
            elif type == 'O':
                self.balance -= transaction.amount
            else:
                pass
            self.save()

    def set_balance_transaction_deleted(self, transaction):
        if transaction.account.id == self.id:
            type = transaction.type
            if type == 'I':
                self.balance -= transaction.amount
            elif type == 'O':
                self.balance += transaction.amount
            else:
                pass
            self.save()

    def __str__(self):
        return '%s (%s)' % (self.name, self.print_balance())

class Transaction(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='transactions', default='')
    amount = models.DecimalField(_('Amount'), max_digits=8, decimal_places=2, validators=[MinValueValidator(0.00)])
    date = models.DateTimeField(_('Date'))
    details = models.CharField(_('Details'), max_length=25, blank=True, null=True)
    category = models.CharField(_('Category'), max_length=3, choices=INCOME_CATEGORY_CHOICES+OUTCOME_CATEGORY_CHOICES)
    INCOME = 'I'
    OUTCOME = 'O'
    TRANSACTION_TYPE_CHOICES = (
        (INCOME, _('Income')),
        (OUTCOME, _('Outcome')),
    )
    type = models.CharField(_('Transaction type'), max_length=1, choices=TRANSACTION_TYPE_CHOICES)

    def print_value(self):
        currency = self.account.currency
        return currency.display(self.amount)

MoneyManagerApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User, Account, Transaction
from MoneyManager.settings import INCOME_CATEGORY_CHOICES, OUTCOME_CATEGORY_CHOICES

class UserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'email')

class AccountCreationForm(forms.ModelForm):

    class Meta:
        model = Account
        fields = ('name', 'balance', 'currency', 'type')

class TransactionCreationForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        transaction_type = kwargs.pop('transaction_type', None)
        super(TransactionCreationForm, self).__init__(*args, **kwargs)
        choices = INCOME_CATEGORY_CHOICES[1:] if transaction_type=='income' else OUTCOME_CATEGORY_CHOICES
        self.fields['category'] =  forms.ChoiceField(choices=choices)

    class Meta:
        model = Transaction
        fields = ('account', 'date', 'category', 'amount', 'details')

MoneyManagerApp/views.py
from django.shortcuts import render
from django.views import generic
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from .models import *
from .forms import *
from django.urls import reverse_lazy, reverse
from django.http import HttpResponse, HttpResponseRedirect
import datetime
from django.conf import settings
from django.http import Http404

class LoginRequiredMixin(object):
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_anonymous:
            return HttpResponseRedirect(reverse_lazy(settings.LOGIN_URL))
        return super().dispatch(request, *args, **kwargs)

class DashboardView(LoginRequiredMixin, generic.ListView):
    template_name = 'moneymanagerapp/dashboard.html'
    context_object_name = 'account_list'
    queryset = ''

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        accounts = self.request.user.accounts.all()
        context['account_list'] = accounts
        context['transactions'] = None
        context['income'] = 0
        context['outcome'] = 0
        selected_account = None
        id = self.kwargs.get('account_id', None)
        if id is None and len(accounts) > 0:
            selected_account = accounts.first()
            id = selected_account.id
        else:
            if accounts.filter(id=id).exists():
                selected_account = accounts.get(id=id)
        if selected_account:
            currency = selected_account.currency
            income = 0
            outcome = 0
            context['transactions'] = selected_account.transactions.order_by('-date')#.filter(date__month=1)
            for transaction in context['transactions']:
                if transaction.type == 'I':
                    income = income + transaction.amount
                else:
                    outcome = outcome - transaction.amount
            context['income'] = currency.display(income)
            context['outcome'] = currency.display(outcome)
        return context

class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('LoginView')
    template_name = 'registration/signup.html'

class AccountCreateView(LoginRequiredMixin, CreateView):
    form_class = AccountCreationForm
    template_name = 'moneymanagerapp/account_form.html'
    success_url = reverse_lazy('DashboardView')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.owner = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

class AccountDeleteView(LoginRequiredMixin, DeleteView):
    model = Account
    template_name = 'moneymanagerapp/account_confirm_delete.html'
    success_url = reverse_lazy('DashboardView')

    def get_object(self, queryset=None):
        object = super(AccountDeleteView, self).get_object()
        if not object.owner == self.request.user:
            raise Http404
        return object

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.owner == request.user:
            self.object.delete()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return HttpResponseRedirect(reverse_lazy('DashboardView'))

class TransactionDeleteView(LoginRequiredMixin, DeleteView):
    model = Transaction
    template_name = 'moneymanagerapp/transaction_confirm_delete.html'
    success_url = reverse_lazy('DashboardView')

    def get_object(self, queryset=None):
        object = super(TransactionDeleteView, self).get_object()
        if not object.account.owner == self.request.user:
            raise Http404
        return object

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.account.owner == request.user:
            self.object.delete()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return HttpResponseRedirect(reverse_lazy('DashboardView'))

class TransactionCreateView(LoginRequiredMixin, CreateView):
    form_class = TransactionCreationForm
    template_name = 'moneymanagerapp/transaction_form.html'
    success_url = reverse_lazy('DashboardView')

    def get_form(self, *args, **kwargs):
        form = super(TransactionCreateView, self).get_form(*args, **kwargs)
        form.fields['account'].queryset = self.request.user.accounts
        return form

    def get_form_kwargs(self):
        kwargs = super(TransactionCreateView, self).get_form_kwargs()
        transaction_type = self.kwargs.get('type', None)
        if transaction_type is None or transaction_type not in ['income', 'outcome']:
            transaction_type = 'income'
        kwargs.update({'transaction_type': transaction_type})
        return kwargs

    def form_valid(self, form):
        self.object = form.save(commit=False)
        transaction_type = self.kwargs.get('type', None)
        if transaction_type is None or transaction_type not in ['income', 'outcome']:
            transaction_type = 'income'
        if transaction_type == 'income':
            self.object.type = 'I'
        elif transaction_type == 'outcome':
            self.object.type ='O'
        else:
            pass
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

MoneyManagerApp/templates/moneymanagerapp/account_confirm_delete.html
{% extends 'moneymanagerapp/base.html' %}
{% load static %}
{% load i18n %}
{% block title %}
{% trans "Delete account" %}
{% endblock title %}
{% block content %}
<form method="post">{% csrf_token %}
   <h2>{% trans "Delete account" %}</h2>
    <p>{% trans "Are you sure you want to delete account" %} <b>{{ object }}</b>?</p>
    <input type="submit" value="{% trans "Confirm" %}"/>
</form>
{% endblock content %}

MoneyManagerApp/templates/moneymanagerapp/account_form.html
{% extends 'moneymanagerapp/base.html' %}
{% load i18n %}
{% block title %}{% trans "Create account" %}{% endblock %}

{% block content %}
  <h2>{% trans "Create account" %}</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{% trans "Create" %}"></input>
  </form>
{% endblock %}

MoneyManagerApp/templates/moneymanagerapp/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html>
    <head>
        <title>MoneyManager - {% block title %}{% endblock %}</title>
        {% block scripts %}{% endblock %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
     	  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'moneymanagerapp/style.css' %}"/>
        <script src="https://code.jquery.com/jquery-3.3.1.min.js" type="text/javascript"></script>
    </head>
    <body>
      <div class="content">
      <header>
      </header>
    {% block content %}{% endblock %}
    </div>
    <footer>
         <p>MoneyManager @ 2020</p>
    </footer>

    </body>
</html>

MoneyManagerApp/templates/moneymanagerapp/dashboard.html
{% extends 'moneymanagerapp/base.html' %}
{% load i18n %}
{% block title %}{% trans "Dashboard" %}{% endblock %}
{% block content %}
<h1>{% trans "Dashboard" %}</h1>
<a href="{% url 'AccountCreateView' %}" ><input type="button" value="{% trans 'Create account' %}"></a>
<a href="{% url 'TransactionCreateView' type='income' %}" ><input type="button" value="{% trans 'Add income' %}"></a>
<a href="{% url 'TransactionCreateView' type='outcome' %}" ><input type="button" value="{% trans 'Add outcome' %}"></a>
<h3>{% trans "Accounts" %}</h3>
<div id="accountsAndNavigation">
   <div class="accountContainerScrollLeft hidden"><</div>
   <div class="accountContainerScrollRight hidden">></div>
      <div id="accounts">
      <div id="accountsContainer">
         {% for account in account_list %}
            <a href="{% url 'DashboardView' account.id %}">
               <div class="account {% if view.kwargs.account_id|add:0 == account.id %}selected{% endif %}">
               <div class="accountName">{{ account.name }}</div>
               <div class="accountBalance">{{ account.print_balance }}</div>
               <a href="{% url 'AccountDeleteView' account.id %}">
               <input type="button" value="{% trans 'Delete account' %}"></a>
            </div></a>
         {% endfor %}
      </div>
   </div>
</div>
{% if transactions %}
   <h4>{% trans "Income" %}: {{ income }}</h4>
   <h4>{% trans "Outcome" %}: {{ outcome }}</h4>
   <h3>{% trans "Transactions" %}</h3>
   <div id="transactions">
         {% for transaction in transactions %}
         <div class="transaction">
            {{ transaction.date|date:'Y-m-d' }} {{ transaction.get_category_display }}
            <span style="color:{% if transaction.type == 'I' %} green {% else %} red {% endif %};">{{ transaction.print_value }}</span>
            {{ transaction.details }} <a href="{% url 'TransactionDeleteView' transaction.id %}" ><input type="button" value="{% trans 'Delete transaction' %}"></a>
         </div>
         {% endfor %}
   </div>
{% else %}
{% trans "Create your first account" %}
{% endif %}
<script>
   function accountsNavigation() {
       var $accountsScrollPos = $("#accounts").scrollLeft();
       var $leftScroll = $('.accountContainerScrollLeft')
       var $rightScroll = $('.accountContainerScrollRight')
       if(!(('ontouchstart' in window) || (navigator.MaxTouchPoints > 0) || (navigator.msMaxTouchPoints > 0))) {
          if ($accountsScrollPos > 0) {
              $leftScroll.removeClass("hidden");
          } else {
              $leftScroll.addClass("hidden");
          }
          if ($(window).width() + $accountsScrollPos < $("#accountsContainer").width()) {
              $rightScroll.removeClass("hidden");
          } else {
              $rightScroll.addClass("hidden");
          }
       }
   }

   $(document).ready(function() {
       accountsNavigation();
       $(window).resize(function() {
           accountsNavigation();
       });
   });

   $("#accounts").scroll(function() {
       accountsNavigation();
   });

   $('.accountContainerScrollLeft').click(function(event) {
       event.preventDefault();
       $('#accounts').animate({
           scrollLeft: "-=216px"
       }, "slow");
   });

   $('.accountContainerScrollRight').click(function(event) {
       event.preventDefault();
       $('#accounts').animate({
           scrollLeft: "+=216px"
       }, "slow");
   });
</script>
{% endblock %}

MoneyManagerApp/templates/moneymanagerapp/transaction_confirm_delete.html
{% extends 'moneymanagerapp/base.html' %}
{% load static %}
{% load i18n %}
{% block title %}
{% trans "Delete transaction" %}
{% endblock title %}
{% block content %}
<form method="post">{% csrf_token %}
   <h2>{% trans "Delete transaction" %}</h2>
    <p>{% trans "Are you sure you want to delete transaction" %} <b>{{ object.details }} ({{ object.print_value }})</b>?</p>
    <input type="submit" value="{% trans "Confirm" %}"/>
</form>
{% endblock content %}

MoneyManagerApp/templates/moneymanagerapp/transaction_form.html
{% extends 'moneymanagerapp/base.html' %}
{% load i18n %}
{% block title %}{% trans "Create transaction" %}{% endblock %}

{% block content %}
<h2>{% blocktrans with transaction_type=view.kwargs.type %}Create {{ transaction_type }} transaction{% endblocktrans %}</h2>
<form method="post">
   {% csrf_token %}
   {{ form.as_p }}
   <input type="submit" value="{% trans "Create" %}"></input>
</form>
<script type="text/javascript">
    function replaceDate() {
    var $currentdate = new Date();
    var $datetime = $currentdate.getFullYear() + "-"
                   + ($currentdate.getMonth()+1)  + "-"
                   + $currentdate.getDate()
   $("#id_date").val($datetime);
}
replaceDate();
</script>
{% endblock %}